### PR TITLE
feat: add mnemonic-based derivation

### PR DESCRIPTION
**Pull request by haardikk21**
## Description
Various mechanisms are being considered to support recovery of private keys in case they're lost. This PR introduces mnemonics based key derivation. Supports converting a key to mnemonic and back.

Would like to get this peer reviewed to ensure no security issues.

- [x] Tests for the changes have been added (for bug fixes / features)
- [x] The commit message(s) follow [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] Documentation has been added / updated (for bug fixes / features)
- [x] Changes follow the **[contributing](../CONTRIBUTING.md)** document.

## Motivation and Context
It is important to provide ways for users to recover their private key deterministically. Useful in cases of using the same key across platforms and devices, and in case of misplacing the key.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Which merge strategy will you use?

- [ ] Squash
- [x] Rebase (REVIEW COMMITS)

### CODE REVIEW

**Comment by haardikk21** [comment]
> Thanks for your PR. I think this would be better outside this repo such that it could be applied to any key and not just BBS+. Is this a copy from Algorand?
> 
> 
> 
> Do you know if this is based on a standard? I can't see if it is in Algorand or here like BIP32

It would be nice to have it in here for ease of use, and allow for reusable mnemonics across platforms using bbs sigs (dont have a use case for that right now, but might happen). I'd understand if you don't want bloat here though I can move it outside. 

It is 99% based on Algorands implementation with a few minor syntactical differences. I'm not 100% sure if they have a standard for this - I've reached out to their engineers and will update once I hear back.

**Comment by mikelodder7** [comment]
I believe it will be better to have this as a separate package as it can be applied to any cryptographic keys.

**Comment by haardikk21** [comment]
> I believe it will be better to have this as a separate package as it can be applied to any cryptographic keys.

Alright. I'll move it outside and drop a link to the repo. Also, to answer your earlier question, the algorithm is not standardized and is a custom implementation. Thanks for reviewing - I'll leave the PR open till I can drop a link to the repo then close it.

**Comment by mikelodder7** [comment]
No problem. Sounds good

**Comment by tplooker** [comment]
@haardikk21 happy if we close this PR?

**Comment by haardikk21** [comment]
Yes, sorry for the delay in posting the repo. I'll share it with you elsewhere.

**Pull request closed without merging**
